# Generated by Django 4.1.4 on 2023-04-10 13:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrudModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('full_text', models.TextField(null=True)),
                ('text', tinymce.models.HTMLField(null=True, verbose_name='Краткое описание новости')),
                ('date', models.DateTimeField(null=True)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
