# Generated by Django 4.1.4 on 2023-04-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crudmodel',
            name='text',
        ),
    ]
