# Generated by Django 4.1.4 on 2023-04-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='crudmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.category'),
        ),
    ]
